services:
  - type: web
    plan: free
    name: wiki
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wiki.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
